export const GET_LOGS = 'GET_LOGS'
export const ADD_LOG = 'ADD_LOG'
export const UPDATE_LOG = 'UPDATE_LOG'
export const DELETE_LOG = 'DELETE_LOG'
export const CLEAR_LOGS = 'CLEAR_LOGS'
export const SEARCH_LOGS = 'SEARCH_LOGS'
export const LOGS_ERROR = 'LOGS_ERROR'

export const GET_TECHS = 'GET_TECHS'
export const ADD_TECH = 'ADD-TECH'
export const UPDATE_TECH = 'UPDATE-TECH'
export const DELETE_TECH = 'DELETE-TECH'
export const CLEAR_TECHS = 'CLEAR-TECHS'
export const SEARCH_TECHS = 'SEARCH-TECHS'
export const TECHS_ERROR = 'TECHS-ERROR'

export const SET_LOADING = 'SET-LOADING'
export const SET_CURRENT = 'SET-CURRENT'
export const CLEAR_CURRENT = 'CLEAR-CURRENT'
